"""Composite transformed section-property helpers.

SECTION.COMPOSITE1A intentionally keeps composite properties separate from the
existing gross-section path.  The functions in this module do **not** modify the
section geometry and do **not** feed PMM/prestress solvers.  They only calculate
an equivalent transformed deck/topping rectangle for future Beam/Girder SLS
workflows.

Coordinate convention follows :mod:`concrete_pmm_pro.geometry.summary`:
coordinates are in mm, y is positive upward, and the precast gross summary is
used exactly as generated by the section geometry module.
"""

from __future__ import annotations

import math
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from concrete_pmm_pro.core.models import SectionGeometry
from concrete_pmm_pro.geometry.summary import GeometrySummary, summarize_geometry


@dataclass(frozen=True)
class CompositeDeckInput:
    """Input metadata for a transformed deck/topping rectangle.

    ``Be_mm`` is the effective deck/topping width in real concrete.  The
    calculation transforms it to the precast/girder concrete basis by multiplying
    by ``n = Edeck/Ebeam``.
    """

    enabled: bool
    Tslab_mm: float
    Be_mm: float
    Ebeam_MPa: float
    Edeck_MPa: float
    deck_centroid_x_mm: float = 0.0
    basis: str = "deck_transformed_to_primary_concrete"

    @property
    def modular_ratio(self) -> float:
        return self.Edeck_MPa / self.Ebeam_MPa

    @property
    def transformed_width_mm(self) -> float:
        return self.modular_ratio * self.Be_mm


@dataclass(frozen=True)
class CompositeTransformedSection:
    """Transformed composite section properties on the primary-concrete basis."""

    active: bool
    area_mm2: float
    centroid_x_mm: float
    centroid_y_mm: float
    ix_mm4: float
    iy_mm4: float
    top_fiber_y_mm: float
    bottom_fiber_y_mm: float
    c_top_mm: float
    c_bottom_mm: float
    z_top_mm3: float | None
    z_bottom_mm3: float | None
    modular_ratio: float
    transformed_width_mm: float
    deck_area_transformed_mm2: float
    deck_centroid_x_mm: float
    deck_centroid_y_mm: float
    precast_area_mm2: float
    precast_centroid_x_mm: float
    precast_centroid_y_mm: float
    warnings: tuple[str, ...] = ()

    @property
    def centroid_y_from_bottom_mm(self) -> float:
        return self.centroid_y_mm - self.bottom_fiber_y_mm

    @property
    def total_depth_mm(self) -> float:
        return self.top_fiber_y_mm - self.bottom_fiber_y_mm


def _finite_positive(value: Any) -> bool:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return False
    return math.isfinite(number) and number > 0.0


def composite_deck_is_active(
    section_parameters: Mapping[str, Any] | None,
    *,
    member_type: str | None = "beam_girder",
    require_explicit_flag: bool = True,
) -> bool:
    """Return whether deck/topping composite calculation should be active.

    Commercial-grade behavior should not infer composite action from a preset
    name.  The safest path is to require an explicit ``composite_enabled`` flag
    plus valid deck/topping geometry and material stiffness data.

    ``require_explicit_flag=False`` is provided only for controlled internal
    validation or migration checks where legacy plank metadata is being examined.
    Production UI should prefer the default ``True``.
    """

    params = dict(section_parameters or {})
    if member_type not in {"beam_girder", "building_beam_girder"}:
        return False
    explicit_enabled = bool(params.get("composite_enabled", False))
    if require_explicit_flag and not explicit_enabled:
        return False
    if not require_explicit_flag and "composite_enabled" in params and not explicit_enabled:
        return False
    return all(
        _finite_positive(params.get(name))
        for name in ("Tslab_mm", "Be_mm", "Ebeam_MPa", "Edeck_MPa")
    )


def composite_deck_input_from_parameters(
    section_parameters: Mapping[str, Any],
    *,
    member_type: str | None = "beam_girder",
    require_explicit_flag: bool = True,
    deck_centroid_x_mm: float | None = None,
) -> CompositeDeckInput:
    """Build deck input from section parameters with conservative activation."""

    params = dict(section_parameters)
    active = composite_deck_is_active(
        params,
        member_type=member_type,
        require_explicit_flag=require_explicit_flag,
    )
    return CompositeDeckInput(
        enabled=active,
        Tslab_mm=float(params.get("Tslab_mm", 0.0) or 0.0),
        Be_mm=float(params.get("Be_mm", 0.0) or 0.0),
        Ebeam_MPa=float(params.get("Ebeam_MPa", 0.0) or 0.0),
        Edeck_MPa=float(params.get("Edeck_MPa", 0.0) or 0.0),
        deck_centroid_x_mm=float(
            params.get("deck_centroid_x_mm", 0.0) if deck_centroid_x_mm is None else deck_centroid_x_mm
        ),
    )


def _section_modulus(inertia_mm4: float, distance_mm: float) -> float | None:
    if distance_mm <= 0.0:
        return None
    return inertia_mm4 / distance_mm


def calculate_composite_transformed_section(
    precast_summary: GeometrySummary,
    deck: CompositeDeckInput,
) -> CompositeTransformedSection:
    """Calculate transformed composite properties for one deck/topping rectangle.

    The deck is placed immediately above the generated precast top fiber:

    ``y_deck_centroid = y_precast_top + Tslab/2``.

    The calculation returns a separate result object and never changes the
    original gross section summary.
    """

    if not deck.enabled:
        raise ValueError("Composite deck/topping is not active.")
    if not _finite_positive(precast_summary.area_mm2):
        raise ValueError("Precast gross area must be positive.")
    if precast_summary.ix_nmm4 is None or precast_summary.iy_nmm4 is None:
        raise ValueError("Precast gross Ix/Iy must be available before composite transformation.")
    if precast_summary.y_max_mm is None or precast_summary.y_min_mm is None:
        raise ValueError("Precast top and bottom fiber coordinates are required.")
    if not _finite_positive(deck.Tslab_mm):
        raise ValueError("Tslab_mm must be positive when composite deck/topping is active.")
    if not _finite_positive(deck.Be_mm):
        raise ValueError("Be_mm must be positive when composite deck/topping is active.")
    if not _finite_positive(deck.Ebeam_MPa) or not _finite_positive(deck.Edeck_MPa):
        raise ValueError("Ebeam_MPa and Edeck_MPa must be positive for transformed composite properties.")

    n_ratio = deck.modular_ratio
    transformed_width = deck.transformed_width_mm
    deck_area = transformed_width * deck.Tslab_mm
    deck_ix_centroid = transformed_width * deck.Tslab_mm**3 / 12.0
    deck_iy_centroid = deck.Tslab_mm * transformed_width**3 / 12.0
    deck_cx = deck.deck_centroid_x_mm
    deck_cy = float(precast_summary.y_max_mm) + deck.Tslab_mm / 2.0

    precast_area = float(precast_summary.area_mm2)
    precast_cx = float(precast_summary.centroid_x_mm)
    precast_cy = float(precast_summary.centroid_y_mm)
    total_area = precast_area + deck_area

    composite_cx = (precast_area * precast_cx + deck_area * deck_cx) / total_area
    composite_cy = (precast_area * precast_cy + deck_area * deck_cy) / total_area

    ix = (
        float(precast_summary.ix_nmm4)
        + precast_area * (precast_cy - composite_cy) ** 2
        + deck_ix_centroid
        + deck_area * (deck_cy - composite_cy) ** 2
    )
    iy = (
        float(precast_summary.iy_nmm4)
        + precast_area * (precast_cx - composite_cx) ** 2
        + deck_iy_centroid
        + deck_area * (deck_cx - composite_cx) ** 2
    )

    top_fiber = float(precast_summary.y_max_mm) + deck.Tslab_mm
    bottom_fiber = float(precast_summary.y_min_mm)
    c_top = top_fiber - composite_cy
    c_bottom = composite_cy - bottom_fiber

    warnings: list[str] = []
    if abs(deck_cx - precast_cx) > max(1.0, 0.05 * (precast_summary.width_mm or 0.0)):
        warnings.append("Deck centroid is offset from the precast centroid; confirm effective-width placement.")

    return CompositeTransformedSection(
        active=True,
        area_mm2=float(total_area),
        centroid_x_mm=float(composite_cx),
        centroid_y_mm=float(composite_cy),
        ix_mm4=float(ix),
        iy_mm4=float(iy),
        top_fiber_y_mm=float(top_fiber),
        bottom_fiber_y_mm=float(bottom_fiber),
        c_top_mm=float(c_top),
        c_bottom_mm=float(c_bottom),
        z_top_mm3=_section_modulus(float(ix), float(c_top)),
        z_bottom_mm3=_section_modulus(float(ix), float(c_bottom)),
        modular_ratio=float(n_ratio),
        transformed_width_mm=float(transformed_width),
        deck_area_transformed_mm2=float(deck_area),
        deck_centroid_x_mm=float(deck_cx),
        deck_centroid_y_mm=float(deck_cy),
        precast_area_mm2=float(precast_area),
        precast_centroid_x_mm=float(precast_cx),
        precast_centroid_y_mm=float(precast_cy),
        warnings=tuple(warnings),
    )


def calculate_composite_transformed_section_from_geometry(
    geometry: SectionGeometry,
    deck: CompositeDeckInput,
) -> CompositeTransformedSection:
    """Convenience wrapper using the existing gross geometry summary."""

    return calculate_composite_transformed_section(summarize_geometry(geometry), deck)
