"""Report foundation, draft Word export, and report QA helpers."""

from concrete_pmm_pro.reporting.readiness import (
    ReportReadinessItem,
    ReportReadinessSummary,
    check_report_readiness,
    report_readiness_to_dataframe,
)
from concrete_pmm_pro.reporting.report_manifest import (
    ReportManifest,
    build_report_manifest,
    generate_plain_text_report_outline,
    report_manifest_to_json_dict,
    report_manifest_to_summary_dataframe,
)
from concrete_pmm_pro.reporting.figure_export import plotly_figure_to_html_bytes, plotly_figure_to_png_bytes
from concrete_pmm_pro.reporting.word_export import (
    ReportExportOptions,
    add_draft_disclaimer,
    add_limitations_section,
    add_page_break,
    add_key_value_table,
    add_report_heading,
    add_report_footer_note,
    add_terminology_section,
    add_unit_conventions_section,
    add_warning_box_or_section,
    apply_document_defaults,
    apply_heading_styles,
    build_draft_word_report,
    dataframe_to_word_table,
    save_draft_word_report,
    set_table_style,
)
from concrete_pmm_pro.reporting.report_qa import (
    ReportQAItem,
    ReportQASummary,
    extract_docx_headings,
    extract_docx_text,
    report_qa_summary_to_dataframe,
    run_word_report_qa,
    validate_draft_disclaimer,
    validate_engineering_limitations_present,
    validate_engineering_warnings_present,
    validate_no_misleading_certification_language,
    validate_report_tables_and_figures_present,
    validate_required_report_headings,
    validate_terminology_present,
    validate_traceability_and_readiness_present,
    validate_unit_conventions_present,
)
from concrete_pmm_pro.reporting.report_models import (
    ReportMetadata,
    ReportSection,
    ReportTableInfo,
    default_report_metadata,
)
from concrete_pmm_pro.reporting.report_figures import (
    ReportFigureContext,
    ReportFigureExportItem,
    build_exportable_figure,
    build_report_figure_context,
    collect_report_figure_export_items,
    report_figure_export_items_to_dataframe,
    safe_report_figure_filename,
)
from concrete_pmm_pro.reporting.report_sections import default_report_section_plan, report_sections_to_dataframe
from concrete_pmm_pro.reporting.report_tables import collect_available_report_tables, report_tables_to_dataframe
from concrete_pmm_pro.reporting.limitations import (
    EngineeringLimitation,
    collect_limitations_for_report,
    deduplicate_limitations_by_key,
    engineering_limitations_to_dataframe,
    get_engineering_limitations,
)
from concrete_pmm_pro.reporting.terminology import EngineeringTerm, get_standard_terminology, terminology_to_dataframe
from concrete_pmm_pro.reporting.traceability import (
    ReportFigureInfo,
    ResultTraceabilitySnapshot,
    build_result_traceability_snapshot,
    collect_available_report_figures,
    collect_engineering_warnings,
    deduplicate_preserve_order,
    report_figures_to_dataframe,
    result_traceability_snapshot_to_dataframe,
)
from concrete_pmm_pro.reporting.units import UnitConvention, get_unit_conventions, unit_conventions_to_dataframe


from concrete_pmm_pro.analysis.railway_u_girder_uls import (
    RAILWAY_UGIRDER_ULS_FLEXURE_EVIDENCE_STATUS,
    RAILWAY_UGIRDER_ULS_FLEXURE_EVIDENCE_WARNING,
    RAILWAY_UGIRDER_ULS_FRAMEWORK_STATUS,
    RAILWAY_UGIRDER_ULS_FRAMEWORK_WARNING,
    RAILWAY_UGIRDER_ULS_SHEAR_EVIDENCE_STATUS,
    RAILWAY_UGIRDER_ULS_SHEAR_EVIDENCE_WARNING,
    RAILWAY_UGIRDER_ULS_TORSION_VT_GUARD_STATUS,
    RAILWAY_UGIRDER_ULS_TORSION_VT_GUARD_WARNING,
    RAILWAY_UGIRDER_PRESTRESS_DEVELOPMENT_STATUS,
    RAILWAY_UGIRDER_PRESTRESS_DEVELOPMENT_WARNING,
    RAILWAY_UGIRDER_ANCHORAGE_END_ZONE_STATUS,
    RAILWAY_UGIRDER_ANCHORAGE_END_ZONE_WARNING,
    RAILWAY_UGIRDER_ULS_TABLE_KEYS,
    RailwayUGirderULSFrameworkPackage,
    build_railway_u_girder_uls_framework_package,
    is_railway_u_girder_uls_context,
    railway_u_girder_uls_flexure_evidence_dataframe,
    railway_u_girder_uls_shear_evidence_dataframe,
    railway_u_girder_uls_torsion_vt_guard_dataframe,
    railway_u_girder_prestress_development_evidence_dataframe,
    railway_u_girder_anchorage_end_zone_evidence_dataframe,
)


from concrete_pmm_pro.reporting.railway_u_girder_release import (
    RAILWAY_UGIRDER_RELEASE_BOUNDARY,
    RAILWAY_UGIRDER_RELEASE_MILESTONE,
    RAILWAY_UGIRDER_RELEASE_STATUS,
    RAILWAY_UGIRDER_RELEASE_TABLE_KEYS,
    RAILWAY_UGIRDER_RELEASE_WARNING,
    RailwayUGirderReleasePackage,
    build_railway_u_girder_release_package,
    railway_u_girder_final_claim_guard_dataframe,
    railway_u_girder_release_manifest_dataframe,
    railway_u_girder_release_readiness_dataframe,
)


from concrete_pmm_pro.reporting.railway_u_girder_final import (
    RAILWAY_UGIRDER_FINAL_CERTIFICATION_BOUNDARY,
    RAILWAY_UGIRDER_FINAL_MILESTONE,
    RAILWAY_UGIRDER_FINAL_STATUS,
    RAILWAY_UGIRDER_FINAL_TABLE_KEYS,
    RAILWAY_UGIRDER_FINAL_WARNING,
    RailwayUGirderFinalDesignCheckPackage,
    build_railway_u_girder_final_design_check_package,
    railway_u_girder_final_certification_boundary_dataframe,
    railway_u_girder_final_design_check_manifest_dataframe,
    railway_u_girder_final_handoff_dataframe,
    railway_u_girder_final_prerequisite_matrix_dataframe,
)

from concrete_pmm_pro.reporting.generic_precast_lifting_report import (
    GENERIC_PRECAST_LIFTING_REPORT_CAPABILITY,
    GENERIC_PRECAST_LIFTING_REPORT_STATUS,
    GENERIC_PRECAST_LIFTING_TABLE_KEYS,
    GenericPrecastLiftingReportPackage,
    build_generic_precast_lifting_report_package,
    generic_precast_lifting_report_tables_to_dataframe,
    is_generic_precast_lifting_report_context,
)

from concrete_pmm_pro.reporting.railway_u_girder_report import (
    RAILWAY_UGIRDER_CLOSEOUT_SCOPE,
    RAILWAY_UGIRDER_CLOSEOUT_STATUS,
    RAILWAY_UGIRDER_REPORT_CAPABILITY,
    RAILWAY_UGIRDER_REPORT_STATUS,
    RAILWAY_UGIRDER_REPORT_TABLE_KEYS,
    RailwayUGirderSLSReportPackage,
    build_railway_u_girder_sls_report_package,
    is_railway_u_girder_report_context,
    railway_u_girder_report_tables_to_dataframe,
)

from concrete_pmm_pro.reporting.column_pier_vt_report import (
    COLUMN_PIER_VT_REPORT_STATUS,
    COLUMN_PIER_VT_REPORT_WARNING,
    COLUMN_PIER_VT_SCOPE_GUARD,
    COLUMN_PIER_VT_TABLE_KEYS,
    ColumnPierVTReportPackage,
    build_column_pier_vt_report_package,
    column_pier_vt_report_tables_to_dataframe,
    is_column_pier_vt_report_context,
)

__all__ = [
    "EngineeringTerm",
    "EngineeringLimitation",
    "ReportFigureInfo",
    "ReportFigureContext",
    "ReportFigureExportItem",
    "ReportExportOptions",
    "ReportManifest",
    "ReportMetadata",
    "ReportQAItem",
    "ReportQASummary",
    "ReportReadinessItem",
    "ReportReadinessSummary",
    "ReportSection",
    "ReportTableInfo",
    "ResultTraceabilitySnapshot",
    "UnitConvention",
    "COLUMN_PIER_VT_REPORT_STATUS",
    "COLUMN_PIER_VT_REPORT_WARNING",
    "COLUMN_PIER_VT_SCOPE_GUARD",
    "COLUMN_PIER_VT_TABLE_KEYS",
    "ColumnPierVTReportPackage",
    "build_column_pier_vt_report_package",
    "column_pier_vt_report_tables_to_dataframe",
    "is_column_pier_vt_report_context",
    "RAILWAY_UGIRDER_FINAL_CERTIFICATION_BOUNDARY",
    "RAILWAY_UGIRDER_FINAL_MILESTONE",
    "RAILWAY_UGIRDER_FINAL_STATUS",
    "RAILWAY_UGIRDER_FINAL_TABLE_KEYS",
    "RAILWAY_UGIRDER_FINAL_WARNING",
    "RailwayUGirderFinalDesignCheckPackage",
    "build_railway_u_girder_final_design_check_package",
    "railway_u_girder_final_certification_boundary_dataframe",
    "railway_u_girder_final_design_check_manifest_dataframe",
    "railway_u_girder_final_handoff_dataframe",
    "railway_u_girder_final_prerequisite_matrix_dataframe",
    "RAILWAY_UGIRDER_RELEASE_BOUNDARY",
    "RAILWAY_UGIRDER_RELEASE_MILESTONE",
    "RAILWAY_UGIRDER_RELEASE_STATUS",
    "RAILWAY_UGIRDER_RELEASE_TABLE_KEYS",
    "RAILWAY_UGIRDER_RELEASE_WARNING",
    "RailwayUGirderReleasePackage",
    "build_railway_u_girder_release_package",
    "railway_u_girder_final_claim_guard_dataframe",
    "railway_u_girder_release_manifest_dataframe",
    "railway_u_girder_release_readiness_dataframe",
    "GENERIC_PRECAST_LIFTING_REPORT_CAPABILITY",
    "GENERIC_PRECAST_LIFTING_REPORT_STATUS",
    "GENERIC_PRECAST_LIFTING_TABLE_KEYS",
    "GenericPrecastLiftingReportPackage",
    "build_generic_precast_lifting_report_package",
    "generic_precast_lifting_report_tables_to_dataframe",
    "is_generic_precast_lifting_report_context",
    "railway_u_girder_report_tables_to_dataframe",
    "is_railway_u_girder_report_context",
    "build_railway_u_girder_sls_report_package",
    "RailwayUGirderSLSReportPackage",
    "RAILWAY_UGIRDER_CLOSEOUT_SCOPE",
    "RAILWAY_UGIRDER_CLOSEOUT_STATUS",
    "RAILWAY_UGIRDER_REPORT_TABLE_KEYS",
    "RAILWAY_UGIRDER_REPORT_STATUS",
    "RAILWAY_UGIRDER_REPORT_CAPABILITY",
    "is_railway_u_girder_uls_context",
    "build_railway_u_girder_uls_framework_package",
    "RailwayUGirderULSFrameworkPackage",
    "RAILWAY_UGIRDER_ULS_TABLE_KEYS",
    "RAILWAY_UGIRDER_ULS_FRAMEWORK_WARNING",
    "RAILWAY_UGIRDER_ULS_FRAMEWORK_STATUS",
    "RAILWAY_UGIRDER_ULS_FLEXURE_EVIDENCE_WARNING",
    "RAILWAY_UGIRDER_ULS_FLEXURE_EVIDENCE_STATUS",
    "RAILWAY_UGIRDER_ULS_SHEAR_EVIDENCE_WARNING",
    "RAILWAY_UGIRDER_ULS_SHEAR_EVIDENCE_STATUS",
    "RAILWAY_UGIRDER_ULS_TORSION_VT_GUARD_WARNING",
    "RAILWAY_UGIRDER_ULS_TORSION_VT_GUARD_STATUS",
    "RAILWAY_UGIRDER_PRESTRESS_DEVELOPMENT_WARNING",
    "RAILWAY_UGIRDER_PRESTRESS_DEVELOPMENT_STATUS",
    "RAILWAY_UGIRDER_ANCHORAGE_END_ZONE_WARNING",
    "RAILWAY_UGIRDER_ANCHORAGE_END_ZONE_STATUS",
    "railway_u_girder_uls_flexure_evidence_dataframe",
    "railway_u_girder_uls_shear_evidence_dataframe",
    "railway_u_girder_uls_torsion_vt_guard_dataframe",
    "railway_u_girder_prestress_development_evidence_dataframe",
    "railway_u_girder_anchorage_end_zone_evidence_dataframe",
    "build_result_traceability_snapshot",
    "build_report_manifest",
    "build_exportable_figure",
    "build_report_figure_context",
    "build_draft_word_report",
    "check_report_readiness",
    "collect_available_report_figures",
    "collect_available_report_tables",
    "collect_engineering_warnings",
    "collect_limitations_for_report",
    "collect_report_figure_export_items",
    "default_report_metadata",
    "default_report_section_plan",
    "dataframe_to_word_table",
    "deduplicate_preserve_order",
    "deduplicate_limitations_by_key",
    "engineering_limitations_to_dataframe",
    "extract_docx_headings",
    "extract_docx_text",
    "generate_plain_text_report_outline",
    "get_standard_terminology",
    "get_engineering_limitations",
    "get_unit_conventions",
    "report_figures_to_dataframe",
    "report_figure_export_items_to_dataframe",
    "report_manifest_to_json_dict",
    "report_manifest_to_summary_dataframe",
    "report_qa_summary_to_dataframe",
    "report_readiness_to_dataframe",
    "report_sections_to_dataframe",
    "report_tables_to_dataframe",
    "plotly_figure_to_html_bytes",
    "plotly_figure_to_png_bytes",
    "run_word_report_qa",
    "save_draft_word_report",
    "add_limitations_section",
    "add_draft_disclaimer",
    "add_key_value_table",
    "add_page_break",
    "add_report_heading",
    "add_report_footer_note",
    "add_terminology_section",
    "add_unit_conventions_section",
    "add_warning_box_or_section",
    "apply_document_defaults",
    "apply_heading_styles",
    "set_table_style",
    "result_traceability_snapshot_to_dataframe",
    "terminology_to_dataframe",
    "unit_conventions_to_dataframe",
    "safe_report_figure_filename",
    "validate_draft_disclaimer",
    "validate_engineering_limitations_present",
    "validate_engineering_warnings_present",
    "validate_no_misleading_certification_language",
    "validate_report_tables_and_figures_present",
    "validate_required_report_headings",
    "validate_terminology_present",
    "validate_traceability_and_readiness_present",
    "validate_unit_conventions_present",
]
