"""Actual app.py routes, native bound/LC review, PNG/CSV and read-only checks.

The section model and alternative LC are hypothetical QA inputs. The U2A
workbook vectors are preserved; this is not the user's complete project.
"""
from contextlib import ExitStack
from copy import deepcopy
import hashlib
import json
import logging
from pathlib import Path
import os
import pickle
import sys
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, 'tests')
import pandas as pd
import streamlit as st
from streamlit.testing.v1 import AppTest
from concrete_pmm_pro.io.project_io import apply_project_to_session_state, project_from_json
from concrete_pmm_pro.io.girder_load_bank import ACTIVE_KEY, BANK_KEY
from concrete_pmm_pro.ui import analysis_page as ap, igird_member_results as mr
from concrete_pmm_pro.ui import igird_uls_report as report, igird_maxmin_charts as mm
from concrete_pmm_pro.ui.igird_case_review import AUTO_CASE, FRAME_KEYS
from concrete_pmm_pro.ui.result_table_display import result_table_for_display
from qa.igird_maxmin10_model import native_model

logging.getLogger('streamlit').setLevel(logging.ERROR)
OUT = Path('qa/evidence/igird_maxmin10/app')
OUT.mkdir(parents=True, exist_ok=True)
state = {}
apply_project_to_session_state(project_from_json(Path('qa/evidence/igird_vtqa1/hypothetical_verified_input_qa.json').read_text()), state)
state.update(native_model())
seed_path = Path(os.environ['CSP_MAXMIN10_UI_SEED']) if os.environ.get('CSP_MAXMIN10_UI_SEED') else None
reused = seed_path is not None and seed_path.is_file()
if reused:
    # Optional checkpoint generated by this script, outside the distributable.
    state = pickle.loads(seed_path.read_bytes())
at = AppTest.from_file(str(Path('app.py').resolve()), default_timeout=90)
for key, value in state.items():
    at.session_state[key] = deepcopy(value)
at.session_state['_nav_active_workspace'] = 'Analysis'
if not reused:
    at.session_state['qa_calculations'] = 0
calculate, render = mr.calculate_member, ap._render_beam_uls_browser_plotly_figure
figures, images = [], []


def counted(*args, **kwargs):
    st.session_state['qa_calculations'] += 1
    return calculate(*args, **kwargs)


def capture(fig, **kwargs):
    if (fig.layout.meta or {}).get('igird_maxmin_check'):
        figures.append(deepcopy(fig))
    render(fig, **kwargs)


def element(items, label):
    return next(item for item in items if item.label == label)


def run():
    figures.clear()
    at.run(timeout=90)
    assert not at.exception, [e.message for e in at.exception]


def guards(stack):
    for name in ('_beam_uls_calculate_selected_check', '_beam_uls_flexure_preview_dataframe',
                 '_beam_uls_igird_torsion_diagram_capacity_dataframe',
                 '_beam_uls_igird_shear_diagram_capacity_dataframe'):
        stack.enter_context(patch.object(ap, name, side_effect=AssertionError('Review solver: '+name)))


def snapshot():
    return {key:pickle.dumps(at.session_state[key]) for key in
            (ACTIVE_KEY, BANK_KEY, 'beam_uls_loads_table', mr.CACHE_KEY,
             ap._BEAM_ULS_MANUAL_CALC_CACHE_KEY)}


def unchanged(previous):
    assert at.session_state['qa_calculations'] == 8
    for key, value in previous.items():
        assert pickle.dumps(at.session_state[key]) == value, key+' changed during review'


def pair(member, lc, check):
    found = [f for f in figures if f.layout.meta['igird_maxmin_member'] == member
             and f.layout.meta['igird_maxmin_check'] == check]
    assert len(found) == 2, [f.layout.title.text for f in figures]
    assert [f.layout.meta['igird_maxmin_step'] for f in found] == ['Max', 'Min']
    assert all(f.layout.meta['igird_maxmin_lc'] == lc for f in found)
    assert all(f.layout.xaxis.range == (0., 20.) for f in found)
    return found


def export(fig, stem):
    from PIL import Image
    path = OUT / (stem+'.png')
    fig.write_json(OUT / (stem+'.plotly.json'))
    fig.write_image(path, width=1440, height=560, scale=2)
    assert Image.open(path).size == (2880,1120)
    images.append(str(path))
    if fig.layout.meta.get('torsion_utilization_audit'):
        pd.DataFrame(fig.layout.meta['torsion_utilization_audit']).to_csv(OUT/(stem+'.strength_audit.csv'),index=False)


records = []
with patch.object(mr, 'calculate_member', counted), patch.object(ap, '_render_beam_uls_browser_plotly_figure', capture):
    run()
    element(at.radio, 'ULS check to calculate').set_value('Flexure')
    run()
    element(at.radio, 'Flexure stage').set_value('Final — Composite')
    run()
    for check in FRAME_KEYS:
        element(at.radio, 'ULS check to calculate').set_value(check)
        run()
        if not reused:
            next(b for b in at.button if b.label.startswith('Calculate '+check+' — all')).click()
            run()
        for member in ('Left Exterior Girder', 'Interior Girder 2'):
            panel = element(at.expander, 'Girder: '+member)
            assert not panel.proto.expanded
            selector = element(at.selectbox, 'Load case to review — '+member)
            assert len(selector.options) == 4  # AUTO, ALL, U2A, QA_LC2
            assert all(f.layout.meta['igird_maxmin_check'] == check for f in figures)
            assert len(panel.get('plotly_chart')) == 2
        records.append({'check':check,'collection_default_separate_max_min':True})
        print('Calculated and rendered native collection: '+check, flush=True)

    if seed_path is not None and not reused:
        seed_path.write_bytes(pickle.dumps(at.session_state.filtered_state))

    original = snapshot()
    with ExitStack() as stack:
        guards(stack)
        stack.enter_context(patch.object(mr, 'calculate_member', side_effect=AssertionError('Review calculation')))
        for check in FRAME_KEYS:
            element(at.radio, 'ULS check to calculate').set_value(check)
            run()
            if check == 'Flexure':
                element(at.radio, 'Flexure stage').set_value('Final — Composite')
                run()
            for lc in ('U2A', 'QA_LC2'):
                for member in ('Left Exterior Girder','Interior Girder 2'):
                    rows = mr.member_inputs(at.session_state.filtered_state)[member]
                    family = next(f for f in mm.csi_bound_families(rows) if f.source['case'] == lc)
                    element(at.selectbox,'Load case to review — '+member).set_value(family.option)
                run()
                for member in ('Left Exterior Girder','Interior Girder 2'):
                    pair(member,lc,check)
                    audit = element(at.expander,'Stored check rows / source audit — '+member).dataframe[0].value
                    family = next(f for f in mm.csi_bound_families(mr.member_inputs(at.session_state.filtered_state)[member]) if f.source['case'] == lc)
                    assert set(audit.Case) == set(family.cases)
                    full = at.session_state[mr.CACHE_KEY][member][check]['result'][FRAME_KEYS[check]]
                    expected = mm.select_cases(full,family.cases)
                    pd.testing.assert_frame_equal(audit.reset_index(drop=True),
                        result_table_for_display(expected).reset_index(drop=True),check_dtype=False,check_exact=True)
            # Single original vector remains available; returning to paired
            # mode restores every occurrence without altering the stored data.
            for radio in [r for r in at.radio if r.label == 'Chart view']:
                radio.set_value(mm.SOURCE_VIEW)
            run()
            assert len([s for s in at.selectbox if s.label.startswith('Source vector to review')]) == 2
            for radio in [r for r in at.radio if r.label == 'Chart view' and mm.SOURCE_VIEW in r.options]:
                radio.set_value(mm.UTILIZATION_VIEW)
            run()
            assert len(figures) == 4
            for member in ('Left Exterior Girder','Interior Girder 2'):
                token = hashlib.sha256(member.encode()).hexdigest()[:16]
                if check != 'Shear + Torsion':
                    at.radio(key='member_'+token+'igird_maxmin_'+check+'_view').set_value(mm.DEMAND_VIEW)
            run()
            # Detailed design-member route also uses the same two bound figures.
            at.toggle(key='igird_compact_details_'+check).set_value(True)
            run()
            assert len(figures) == 6
            assert any(b.label == ('Calculate Final Composite Flexure' if check == 'Flexure' else 'Calculate '+check) for b in at.button)
            at.toggle(key='igird_compact_details_'+check).set_value(False)
            run()
            unchanged(original)
            print('Read-only LC/source/detail review passed: '+check, flush=True)

        at.session_state['_nav_active_workspace'] = 'Report / QA'
        run()
        report_records = []
        for check, label in report.CHECK_LABELS.items():
            element(at.selectbox, 'ULS check for report chart').set_value(label)
            run()
            for index, member in enumerate(('Left Exterior Girder','Interior Girder 2')):
                element(at.selectbox,'Girder for report chart').set_value(member)
                run()
                packages = report.current_check_packages(at.session_state.filtered_state, check)
                for family in mm.csi_bound_families(packages[member]['rows']):
                    element(at.selectbox,'Load case for report chart').set_value(family.option)
                    run()
                    found = pair(member,family.source['case'],check)
                    for fig in found:
                        step = fig.layout.meta['igird_maxmin_step']
                        stem = check.lower().replace(' + ','_')+'_'+str(index)+'_'+str(family.source['case']).lower()+'_'+step.lower()
                        export(fig, stem)
                    checked = element(at.expander,'Report chart — load-case ranking / source audit').dataframe[-1].value
                    assert set(checked.Case) == set(family.cases)
                    checked.to_csv(OUT/(stem.rsplit('_',1)[0]+'.stored_checks.csv'),index=False)
                element(at.button,'Create report chart PNG').click()
                run()
                labels = {d.proto.label for d in at.get('download_button')}
                assert {'Download Max report chart PNG','Download Min report chart PNG',
                        'Download selected stored check rows (CSV)'} <= labels
                if check == 'Torsion':
                    element(at.radio,'Chart view').set_value(mm.UTILIZATION_VIEW)
                    run()
                    for fig in pair(member,family.source['case'],check):
                        step=fig.layout.meta['igird_maxmin_step']
                        assert fig.layout.meta['torsion_utilization_audit']
                        export(fig,'torsion_'+str(index)+'_'+family.source['case'].lower()+'_'+step.lower()+'_utilization')
                    element(at.button,'Create report chart PNG').click()
                    run()
                    assert len([d for d in at.get('download_button') if d.proto.label == 'Download torsion utilization station audit (CSV)']) == 2
                    element(at.radio,'Chart view').set_value(mm.DEMAND_VIEW)
                    run()
            unchanged(original)
            report_records.append({'check':check,'members':2,'LC_per_member':2,'separate_bound_charts':8,
                                   'paired_check_csv':True,'two_PNG_download_widgets':True,'review_solver_calls':0})
            print('Report, source CSV and Max/Min PNG passed: '+check, flush=True)

        bank = deepcopy(at.session_state[BANK_KEY])
        bank.loc[bank.Girder.eq('Interior Girder 2'), 'Mux'] *= 1.5
        at.session_state[BANK_KEY] = bank
        run()
        assert element(at.selectbox,'Girder for report chart').options == ['Left Exterior Girder']
        assert any('Interior Girder 2' in w.value and 'No current' in w.value for w in at.warning)
        bank.loc[bank.Girder.eq('Left Exterior Girder'), 'Mux'] *= 1.5
        at.session_state[BANK_KEY] = bank
        loads = deepcopy(at.session_state['beam_uls_loads_table'])
        loads.Mux *= 1.5
        at.session_state['beam_uls_loads_table'] = loads
        run()
        assert not any(b.label == 'Create report chart PNG' for b in at.button)
        assert at.session_state[ACTIVE_KEY] == 'Left Exterior Girder'

evidence = {'release':'IGIRDER.MAXMIN10','status':'PASS','entrypoint':'app.py',
    'scope':'Archived CSI force vectors and hypothetical section / alternative LC; not user-project approval or live deployment',
    'streamlit_exceptions':0,'calculate_member_calls':8,'review_solver_calls':0,
    'collection':records,'report':report_records,'input_cache_design_member_preserved':True,
    'stale_members_hidden':True,'PNG_size_px':[2880,1120],'PNG_files':images}
(OUT/'app_integration.json').write_text(json.dumps(evidence,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(evidence,ensure_ascii=False),flush=True)
