"""Final export/control-marker check using stored QA production results.

An optional CSP_MAXMIN10_UI_SEED is the local checkpoint generated by the
app verification script. Without it, calculate the hypothetical QA model first.
"""
from contextlib import ExitStack
import json
import os
from pathlib import Path
import pickle
import sys
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from PIL import Image
from concrete_pmm_pro.ui import analysis_page as ap, igird_member_results as mr
from concrete_pmm_pro.ui import igird_uls_report as report, igird_maxmin_charts as mm
from concrete_pmm_pro.io.girder_load_bank import ACTIVE_KEY, BANK_KEY
from qa.igird_maxmin10_model import calculate_native_model

seed = os.environ.get('CSP_MAXMIN10_UI_SEED')
state = pickle.loads(Path(seed).read_bytes()) if seed else calculate_native_model()
out = Path('qa/evidence/igird_maxmin10/app')
out.mkdir(parents=True, exist_ok=True)
keys = (ACTIVE_KEY, BANK_KEY, 'beam_uls_loads_table', mr.CACHE_KEY, ap._BEAM_ULS_MANUAL_CALC_CACHE_KEY)
before = {key:pickle.dumps(state.get(key)) for key in keys}
records = []
with ExitStack() as stack:
    for name in ('_beam_uls_calculate_selected_check', '_beam_uls_flexure_preview_dataframe',
                 '_beam_uls_final_composite_preparation', '_beam_uls_igird_shear_diagram_capacity_dataframe',
                 '_beam_uls_igird_torsion_diagram_capacity_dataframe'):
        stack.enter_context(patch.object(ap, name, side_effect=AssertionError('Export must not solve')))
    stack.enter_context(patch.object(mr, 'calculate_member', side_effect=AssertionError('Export must not calculate')))
    for check in report.CHECK_LABELS:
        packages = report.current_check_packages(state, check)
        assert len(packages) == 2
        for index, member in enumerate(('Left Exterior Girder', 'Interior Girder 2')):
            package = packages[member]
            for family in mm.csi_bound_families(package['rows']):
                views = ([mm.UTILIZATION_VIEW] if check == 'Shear + Torsion' else [mm.DEMAND_VIEW])
                if check == 'Torsion' and family.source['case'] == 'QA_LC2':
                    views.append(mm.UTILIZATION_VIEW)
                for view in views:
                    figures = mm.make_bound_figures(state, package, family=family, member=member,
                        check_name=check, code_label='AASHTO LRFD 9th Edition', view=view)
                    for step, fig in figures.items():
                        meta = fig.layout.meta
                        assert '◆ at foot: control station.' in meta['igird_report_note'][0]
                        marker = meta['igird_maxmin_control_marker']
                        if marker:
                            annotation = next(a for a in fig.layout.annotations if a.name == 'igird_maxmin_control')
                            assert annotation.x == marker['x_m'] and annotation.yref == 'paper'
                            assert marker['Ratio'] == meta['igird_maxmin_selected_control']['D/C or ratio']
                            assert marker['Case'] == meta['igird_maxmin_selected_control']['Controlling load case']
                        stem = check.lower().replace(' + ','_')+'_'+str(index)+'_'+family.source['case'].lower()+'_'+step.lower()
                        if check == 'Torsion' and view == mm.UTILIZATION_VIEW:
                            stem += '_utilization'
                        fig.write_json(out/(stem+'.plotly.json'))
                        fig.write_image(out/(stem+'.png'), width=1440, height=560, scale=2)
                        assert Image.open(out/(stem+'.png')).size == (2880,1120)
                        records.append({'file':stem+'.png','check':check,'member':member,
                            'LC':family.source['case'],'ItemType':step,'view':view,
                            'control_marker':marker})
for key,value in before.items():
    assert pickle.dumps(state.get(key)) == value, key+' changed during export'
evidence = {'release':'IGIRDER.MAXMIN10','status':'PASS','export_solver_calls':0,
    'input_cache_design_member_preserved':True,'PNG_size_px':[2880,1120],
    'images':records,'scope':'Stored hypothetical QA model; not user-project approval'}
Path('qa/evidence/igird_maxmin10/final_export_verification.json').write_text(json.dumps(evidence,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':'PASS','images':len(records),'export_solver_calls':0}),flush=True)
